# Generated by Django 5.0.4 on 2024-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="File",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="comments",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
